const { Router } = require('express');
const { authenticate } = require('../middleware/auth');
const { parseContract } = require('../services/contractParserService');
const { generateFromFields, generateFromText } = require('../services/contractGeneratorService');
const contractStore = require('../models/contractStore');

const router = Router();
router.use(authenticate);

/**
 * POST /contracts/parse
 *
 * Parse a written contract document and extract structured fields.
 * Useful for pre-filling a rental form from an existing contract.
 *
 * Body: { document: "<full contract text>" }
 *
 * Returns:
 *   fields   - extracted values (null for any not found)
 *   found    - list of successfully extracted field names
 *   missing  - list of field names that could not be found
 */
router.post('/parse', (req, res) => {
  const { document } = req.body;
  try {
    const result = parseContract(document);
    res.json(result);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

/**
 * POST /contracts/parse/rental
 *
 * Parse a contract document AND create a rental session from it.
 * Extracts itemName (and optionally address) to open a new rental.
 *
 * Body: { document: "<full contract text>" }
 */
router.post('/parse/rental', (req, res) => {
  const { document } = req.body;

  let parsed;
  try {
    parsed = parseContract(document);
  } catch (err) {
    return res.status(400).json({ error: err.message });
  }

  const itemName = parsed.fields.itemName || parsed.fields.address;
  if (!itemName) {
    return res.status(422).json({
      error: 'Could not determine rental item from document. Please ensure the contract mentions what is being rented.',
      fields: parsed.fields,
    });
  }

  const rentalService = require('../services/rentalService');
  let rental;
  try {
    rental = rentalService.startRental(req.user.id, itemName);
  } catch (err) {
    return res.status(400).json({ error: err.message });
  }

  res.status(201).json({
    fields: parsed.fields,
    found: parsed.found,
    missing: parsed.missing,
    rental,
  });
});

/**
 * POST /contracts/generate
 *
 * Generate a tenancy contract.
 *
 * Accepts one of two modes controlled by the `mode` field:
 *
 *   mode: "fields"  (default)
 *     Supply structured fields directly:
 *     { tenantName, landlordName, address, startDate, endDate,
 *       duration, rentAmount, rentFrequency, depositAmount,
 *       itemName, additionalTerms }
 *
 *   mode: "text"
 *     Supply a free-text description and let the AI parse it:
 *     { text: "John rents his flat at 12 Baker St to Sarah for 6 months
 *              starting 1 April 2025 at £900/month" }
 *
 * Returns: { id, contract, fields, missing, createdAt }
 */
router.post('/generate', (req, res) => {
  const { mode = 'fields', text, ...fields } = req.body;

  let result;
  try {
    if (mode === 'text') {
      if (!text) return res.status(400).json({ error: 'text is required when mode is "text"' });
      result = generateFromText(text);
      result.source = 'text';
      result.originalText = text;
    } else {
      result = generateFromFields(fields);
      result.source = 'fields';
      result.missing = Object.keys(fields).filter(
        (k) => !fields[k] && ['tenantName', 'landlordName', 'address', 'startDate', 'rentAmount'].includes(k)
      );
    }
  } catch (err) {
    return res.status(400).json({ error: err.message });
  }

  const record = contractStore.create({
    userId:       req.user.id,
    contract:     result.contract,
    fields:       result.fields,
    source:       result.source,
    originalText: result.originalText || null,
  });

  res.status(201).json({
    id:        record.id,
    contract:  record.contract,
    fields:    record.fields,
    missing:   result.missing || [],
    createdAt: record.createdAt,
  });
});

/**
 * GET /contracts
 *
 * List all contracts generated by the authenticated user (summary, no full text).
 */
router.get('/', (req, res) => {
  const contracts = contractStore.findAllByUser(req.user.id);
  res.json({ contracts });
});

/**
 * GET /contracts/:id
 *
 * Get a single contract (including full text) by ID.
 */
router.get('/:id', (req, res) => {
  const record = contractStore.findById(req.params.id);
  if (!record) {
    return res.status(404).json({ error: 'Contract not found' });
  }
  if (record.userId !== req.user.id) {
    return res.status(403).json({ error: 'Not authorized to view this contract' });
  }
  res.json(record);
});

module.exports = router;
